sophiemoustard/compani-outils

- App/index.tsx
- app.json
- environment.ts
- package-lock.json
- package.json
master en api)
- Oui parce que pas d'utilisation de l'api
- J'ai ajouté une variable d'environnement :
***Pour recupérer la variable DSN : Sentry --> mobile-erp --> Settings --> client Keys***
- Cas d'usage : si j'ai une erreur elle apparait sur Sentry.
Pour tester il faut ajouter : `enableInExpoDevelopment: true` et changer `debug: true` dans App/index.tsx
Je n'ai pas renommé l'app formation car je ne suis pas sure que l'on puisse. On utilise le nom du projet dans app.json et j'ai l'impression que cette config n'est utilisé que sur les publish donc je ne peux pas encore testé si ca fonctionne en renommant le projet. 
https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/uploading/ …
> COM-2023 add sentry to app

- src/AppNavigation/index.tsx
- src/api/Authentication.ts
- src/context/AuthContext.ts
- src/context/createAuthContext.tsx
- src/core/data/constants.ts
- src/core/helpers/asyncStorage.ts
- src/core/helpers/dates.ts
- [] J'ai testé sur android - Problème avec mon simulateur, des erreurs apparaissent ( y compris lorsque je suis sur la branche dev) 
master en api)
- Oui parce que j'utilise une route déjà existante sans la modifier
- Cas d'usage : lorsque je ferme l'application puis la rouvre je reste connecté tant que refreshToken est valide
Pour tester il faut: 
- modifier `TOKEN_EXPIRE_TIME` dans alenvi-api  src/models/Users.js (par exemple le passer a 15s)
- modifier `refreshTokenExpireDate ` dans alenvi-erp-mobile src/core/helpers/asyncStorage.ts (par exemple le passer a 60s : new Date(Date.now() + 60000)
> Com 2018 stay connected

- src/context/AuthContext.ts
- src/core/helpers/asyncStorage.ts
Je supprime le refreshToken lorsque je me déconnecte.
> COM-2018 delete refreshToken when user logs out

- src/components/form/PrimaryButton/index.tsx
- src/components/form/SecondaryButton/styles.tsx
- src/screens/Authentication/index.tsx
- src/screens/Authentication/styles.ts
- src/screens/Profile/styles.ts
- [] J'ai testé sur android - Problème avec mon simulateur, des erreurs apparaissent ( y compris lorsque je suis sur la branche dev) 
- Cas d'usage : lorsque j'ouvre l'application, j'ai la possibilité d'appuyer sur le bouton `C'est ma première connexion`. Je suis redirigé vers la page `mot de passe oublié`
> Com 2022 - first connexion 

- src/components/form/Input/styles.ts
- src/components/modals/ForgotPasswordModal/index.tsx
- src/components/modals/ForgotPasswordModal/styles.ts
- src/screens/ForgotPassword/styles.ts
- src/styles/common.ts
- src/styles/metrics.ts
Nouvelle modal pour le mot de passe oublié
Cas de test : quand l'api esst en maintenance et que je clique pour recevoir le code par SMS / email, je vois la modal de maintenance
> COM-2016 - do not use modal component

- src/screens/Profile/styles.ts
Modify subtitle style : FIRA_SANS_REGULAR --> FIRA_SANS_MEDIUM
> COM-2045 review style for subtitles

- src/api/Events.ts
- src/core/data/constants.ts
- src/core/helpers/utils.ts
- src/screens/TimeStampingProfile/index.tsx
- src/screens/TimeStampingProfile/style.ts
- src/types/EventType.ts
- Cas d'usage : 
En allant sur la page `Horodatage`, l'auxiliaire voit la date du jour et l'heure. L'auxiliaire voit également le nombre d'évènements de la journée. 
La prochaine étape va être d'afficher le détail de chaque événement: nom du bénéficiaire, heure d'arrivée et de départ (planifiées) de l'auxiliaire.
Avant de tester penser à créer un profil auxiliaire en local et y ajouter des événements sur le planning ou utiliser un id d'auxiliaire existant pour le mettre dans `const params = { auxiliary: 'id' ... }` .
> Com 2048- TimeStamping Screen

- src/screens/ForgotPassword/index.tsx
**sur une telephone physique**
quand je fais mot de passe oublié, au moment ou je clique pour entre le code,  le clavier apparait et l'affiachage se casse - cf capture ci-dessus. je corrige ca dans cette PR
> COM-2016 - fix keyboard display

- src/api/Users.ts
- src/components/PasswordForm/index.tsx
- src/components/PasswordForm/styles.ts
- src/components/form/Input/index.tsx
- src/components/modals/ForgotPasswordModal/index.tsx
- src/navigation/AppNavigation/index.tsx
- src/screens/Authentication/index.tsx
- src/screens/ForgotPassword/index.tsx
- src/screens/PasswordReset/index.tsx
- src/styles/metrics.ts
Périmètre de cette PR : 
- Dans le process de mot de passe oublié, quand je rentre le code (reçu par mail), je suis redirigé vers une page pour changer mon mot de passe
- Je peux rentrer mon nouveau mot de passe et sa confirmation
- Quand je clique sur valider : 
-- si le mot de passe a moins de 6 caractères, j'ai un message d'erreur
-- si la confirmation est différente,  j'ai un message d'erreur
-- Si tout est bon, mon mot de passe est enregistré et j'arrive sur la page d'horodatage
> Com 2021 set passsword

- app.json
master en api)-np
- Cas d'usage : changements npm package + bundleIdentifier. 
J'ai teste que l'app se lancait bien. J'ai teste firebase aussi, mais ils ont peu de sens vu que c'est la partie web qui est testé
> COM-2025 rename bundleIdentifier + package

- app.json
master en api) -np
- Cas d'usage : ajout des versions
> add buildnumber and versionCode

- src/components/TimeStampingCell/index.tsx
- src/context/AuthContext.ts
- src/core/data/constants.ts
- src/core/helpers/asyncStorage.ts
- src/core/helpers/dates.ts
- src/core/helpers/utils.ts
- src/screens/TimeStampingProfile/index.tsx
- src/screens/TimeStampingProfile/styles.ts
master en api)
- Cas d'usage : lorsque l'auxiliaire de vie se connecte, il accède a la page horodatage depuis laquelle il voit toutes les interventions du jour. 
Dans cette PR, j'ai modifié l'affichage de la date et de l'heure pour la plateforme android, j'ai ajouté une marge en bas de la page et mis le nom des bénéficiaires en majuscule.
> Com 2048 time stamping screen - format Date for android platform

- package-lock.json
- package.json
- src/components/RadioButtonList/index.tsx
- src/components/RadioButtonList/styles.ts
- src/screens/timeStamping/ManualTimeStamping/styles.ts
master en api)
- Oui 
- Cas d'usage : ajout des RadioButton permettant a l'utilisateur de sélectionner un motif d'horodatage manuel.
Au départ, je pensais utiliser `react-native-bouncy-checkbox` mais l'état de chaque bouton n'était pas bien géré par ce package. Comme nous devons gérer l'état de chaque bouton, Chloé m'a suggéré de créer notre propre composant contenant l'icône et le text plutôt que d'utiliser ce package.
> Com 2073 add radioButton

- src/components/TimeStampingCell/styles.ts
- src/screens/timeStamping/TimeStampingProfile/styles.ts
master en api)
- Si j'en envoie un nouveau, explication et gestion de la compatibilite: 
- Cas d'usage : Modification de la taille de l'heure
> COM-2048 review hour size

- src/api/Events.ts
- src/components/RadioButtonList/index.tsx
- src/screens/timeStamping/ManualTimeStamping/index.tsx
- src/screens/timeStamping/ManualTimeStamping/styles.ts
master en api)
- Non parce que creation d'une route d'horodatage 
- Cas d'usage : Je peux horodater la date de debut d'un evenement - pour l'instant pour tester il faut aller voir en bdd.
> Com 2073 timestamp

- src/core/data/constants.ts
- src/screens/ProfileEdition/index.tsx
master en api)
- Oui 
- Cas d'usage : Lorsque l'utilisateur clique sur "Valider", si l'un des champs n'est pas valide alors un message d'erreur s'affiche sous le champ correspondant. Le message d'erreur disparaît quand l'utilisateur a renseigné du contenu valide pour le champ.
Je viens de relire tout le ticket et il y a une partie de BACK que je n'ai pas faite: 
```
BACK: 
dans authentication : mettre le droit user/edit/{id} à tout le monde
prehandler authorizeuserupdate: si auxiliary_without_company, juste autoriser à modifier nom, prénom, mail, téléphone
```
comment voulez-vous que l'on s'organise? Est-ce qu'on prévoit de la faire en pp demain matin?
> COM-2046 manage errors

- src/components/TimeStampingCell/index.tsx
- src/components/TimeStampingCell/styles.ts
- src/types/EventType.ts
- [] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
master en api)
- Non parce que on attend les historiques mais ce n'est pas grave car l'app n'est pas encore en production
- J'ai ajouté une variable d'environnement :
- Cas d'usage : Quand la fin d'une intervention est horodatée, je vois le voyant vert
> COM-2075 - add end hour time stamp

- src/components/TimeStampingCell/index.tsx
- src/components/TimeStampingCell/styles.ts
- src/components/form/SecondaryButton/index.tsx
- src/components/form/SecondaryButton/styles.tsx
- src/screens/timeStamping/ManualTimeStamping/index.tsx
- src/screens/timeStamping/TimeStampingProfile/index.tsx
master en api)
- Oui parce que pas en prod 
- Cas d'usage : changement style bouton + changement messages d'erreurs
> Fix timestamp

- package-lock.json
- package.json
- src/AppContainer/index.tsx
- src/context/AuthContext.ts
- src/context/createAuthContext.tsx
master en api)
- Oui parce qu'il n'y a pas de changement dans les appels fait au back ni le retour traité
- ~~J'ai ajouté une variable d'environnement :~~
- Cas d'usage : Suppression de `// eslint-disable-next-line react-hooks/exhaustive-deps` -> le `loggedUser` n'est mis a jour dans le store que s'il change
> Stop infinite loop use authcontext in use effect

- environment.ts
master en api)
- Oui parce que pas d'implication back
- Cas d'usage : 
si j'ai les variables d'environnement : 
- que je me connecte avec un compte classique --> tout se passe bien 
- que je me connecte avec le compte de testEmail et testId --> ca renvoie bien vers dev
Si je n'ai pas les variables d'environnement tout se passe bien
> COM-2237 fix when no environment variables

- src/screens/timeStamping/QRCodeScanner/index.tsx
master en api)
- Oui parce que je ne modifie que l'aspect
- ~~[ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas~~
- ~~[ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas.~~
- ~~J'ai ajouté une variable d'environnement :~~
- Cas d'usage : l'image n'est plus distordue à l'ouverture du QR Code
> Com 2189 distortion

- src/screens/timeStamping/QRCodeScanner/index.tsx
je refuse l’autorisation => j’ai la modale => je redemande l’autorisation et cette fois j’accepte => ça débloque bien l’appareil photo et je n'ai plus la modal “vous n’avez pas autorisé...” visible à l’écran
> COM-2189 - Fix Ulysse review

- app.json
> test interne - 02/07

- src/components/PasswordForm/index.tsx
- src/screens/ForgotPassword/index.tsx
- src/screens/ProfileEdition/index.tsx
master en api)
- Oui parce que je modifie juste du texte
- ~~[ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas~~
- ~~[ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas.~~
- ~~J'ai ajouté une variable d'environnement :~~
- Cas d'usage : formes inclusives sur : 
- les modales lorsqu'on quitte l'édition du mot de passe/du profil, mot de passe oublié
> COM-2109: inclusive forms

- src/components/PasswordForm/index.tsx
- src/components/modals/CameraAccessModal/index.tsx
- src/components/modals/ExitModal/styles.ts
- src/components/modals/ForgotPasswordModal/index.tsx
- src/core/helpers/dates.ts
- src/screens/ForgotPassword/index.tsx
- src/screens/ProfileEdition/index.tsx
- src/screens/timeStamping/EventEdition/index.tsx
- src/screens/timeStamping/TimeStampingProfile/index.tsx
master en api)
- ~~[ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas~~
- ~~[ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas.~~
- ~~J'ai ajouté une variable d'environnement :~~
Fix des reviews de Romain sur le ticket 2470
> COM-2470 - Fix Romain's reviews

- src/components/modals/ExitModal/styles.ts
Fix d'un bug remonté par Ulysse sur les petits écrans (testé sur iphone SE, iphone 8, android pixel 2)
> COM-2470 - Fix css

- src/components/EventAuxiliaryEdition/index.tsx
- src/components/EventAuxiliaryEdition/styles.ts
- src/screens/timeStamping/EventEdition/index.tsx
master en api)
- Cas d'usage : Lorsqu'une intervention est horodatée, je ne peux pas editer l'intervenant.
> COM-2531 - can't edit auxiliary if event is timeStamped

- src/components/EventAuxiliaryEdition/index.tsx
- src/components/EventAuxiliaryEdition/styles.ts
- src/components/EventAuxiliaryEditionModal/index.tsx
- src/screens/timeStamping/EventEdition/index.tsx
- src/screens/timeStamping/EventEdition/styles.ts
- src/styles/metrics.ts
- [] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
master en api)
- Cas d'usage : Lorsque l'intervention est facturée, je ne peux pas éditer l'auxiliaire.
> COM-2523 - can't edit auxiliary if event is Billed

- app.json
> mep-0312 - version number

- app.json
> MEP-1712 version number

- .github/pull_request_template.md
<details><summary> TESTS  :computer: </summary>
</details>
---
<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>
</details>
- Périmètre interfaces / rôles :
> COM-2599 change checklists

- .github/pull_request_template.md
---
---
- Périmètre interfaces / rôles :
> COM-2599 remove useless sections

- src/components/EventCell/index.tsx
- src/components/EventCell/styles.ts
Fix de la cellule d'évènement après suppression du correctif dans un rebase de la PR : [COM-2728](https://github.com/sophiemoustard/compani-outils/pull/161)
> Fix css after rebase in COM-2728

- src/components/EventCell/index.tsx
---
---
- Cas d'usage : Retour de Romain:  La coche me semble plus grosse sur l'événement que sur les maquettes figma, peut-on essayer de s’approcher un peu plus du design des maquettes ? 
- Comment tester ? : horodater une intervention
> COM-2739-fix - resize icons

- app.json
> Mep 180322

- app.json
Versions 1.9.0 / 20 - 15/04/2022
> MEP-1504 - version numbers

- src/components/modals/ForgotPasswordModal/index.tsx
- src/core/helpers/utils.ts
- src/screens/Authentication/index.tsx
- src/screens/ForgotPassword/index.tsx
- src/screens/ProfileEdition/index.tsx
---
---
- Périmètre interfaces / rôles : mobile / auxiliaire
- Cas d'usage : je peux me connecter ou réinitialiser mon mot de passe même si mon mail est mal formatté
- se connecter normalement
- réinitialiser son mot de passe (avec code SMS et mail) normalement
- refaire les deux étapes précédentes mais en rajoutant un espace (avant ou après le mail) => ça fonctionne quand même 
> COM-2806: trim email

- app.json
> mep-20-06: build versions

- app.json
> MEP-2207 - version numbers

- .github/pull_request_template.md
ajout du test sur tablette dans les tests de PR
> COM-2973: add tablet test on github

- .github/workflows/integration-tests.yml
- environment.ts
---
---
- Cas d'usage : je peux utiliser l'app en staging
- Comment tester ? : vérifier que l'app fonctionne bien sur l'environnement de staging (lien sur slack)
> Staging env
