- .github/pull_request_template.md
- .github/workflows/ts-lint.yml
- package.json
- tsconfig.json
Checklist : pas de changement par rapport à celle de l'app mobile formation
Typescript : quelques changements : 
- J'ai enlevé `declaration` et `outdir` car ils permettaient de créer des fichiers alors que `noEmit` indique justement de ne pas les créer
- j'ai passé `noImplicitAny` a true. Je me suis dit que si il etait a true cela permettrait de nous forcer à utiliser typescript au maximum. A voir si a l'usage c'est trop embetant ? 
- J'ai enlevé `include` --> je me suis dit qu'on voulait tester tous les fichiers ? (idem a voir à l'usage)
J'ai déplacé `allowSyntheticDefaultImports` pour qu'il soit a coté de `esModuleInterop` car le fait d'avoir `esModuleInterop` met par defaut la valeur de `allowSyntheticDefaultImports` à true. Je me suis dit qu'on pouvait tout de meme conserver les deux …
> Ajout checklist + typescript

- src/AppContainer/index.tsx
- src/api/Users.ts
- src/api/Versions.ts
- src/context/AuthContext.ts
- src/context/createAuthContext.tsx
- src/hooks/useAxios.ts
- src/screens/ForgotPassword/index.tsx
C'est un proposition pour gérer nos appels à axios avec les intercepteurs. 
L'idée si on continue dans cette voie serait de créer `useCompaniAxios` pour gérer les appels qui nécessite d’être connecté
**Qu'en pensez vous ?**
Je n'ai changé que 2 routes: 
- celle coté mot de passe oublié pour savoir si l'email est relié a un compte existant
- celle pour vérifier s'il faut mettre a jour l'application
Je changerai les autres routes une fois qu'on se sera mis d'accord sur la bonne solution
> Com 2016 use axios

- package-lock.json
- package.json
Tous les packages étaient bien à jour.
J'ai supprimé deux d'entre eux: `react-native-reanimated` et `react-native-web`. On ne se sert pas de ces packages, ils ont été installés par défaut par expo
> Com 2056 - npm update

- app.json
master en api)
- Oui parce que changement que dans app.json
- Cas d'usage : https://docs.expo.io/versions/v41.0.0/config/app/#permissions le changement permet de ne demander qu'un minimum de permission a l'utilisateur sur android
> add android permissions

- package-lock.json
- package.json
Mise a jour des paquets: 
- sentry-expo : 3.1.0 --> 3.1.4  Fix bugs + mise a jour des dépendances expo https://github.com/expo/sentry-expo/blob/master/CHANGELOG.md
- expo: 41.0.0 --> 41.0.1 Pas de changelog
Il y a quelques warning présents sur des dépendances (uniquement sur des paquets présents dans `package-lock.json`) . Je ne sais pas a quel point ces warnings sont alertant
> COM-2080 expo update

- src/api/Events.ts
- src/screens/timeStamping/ManualTimeStamping/index.tsx
- [] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
master en api) -np
- Si j'en envoie un nouveau, explication et gestion de la compatibilite: app pas en prod
- Cas d'usage : Je peux horodater la fin d'une intervention
> COM-2074 can timestamp end of intervention

- package-lock.json
- package.json
master en api)
- Oui 
Mise a jour du paquet : 
- sinon: ^10.0.0 -> ^11.0.0: fixe bugs + avertissement lors de potentielles fuites de mémoire: https://github.com/sinonjs/sinon/blob/master/docs/changelog.md
⚠️ 2 vulnérabilités sont liées a `node-fetch` qui est une dépendance de `sentry-expo`. Pour l'instant elles ne sont pas fixées par la dernière version de `sentry-expo` (version 3.1.3), nous avons donc laissé le paquet a la version voulue par expo (version 3.1.0). Point d'attention sur ce paquet pour les prochaines maj.
> Com 2108 npm update

- package-lock.json
- package.json
master en api)
- Oui 
Pas de MAJ de paquets, uniquement des MAJ de dépendances de paquets.
⚠️ Toujours le même point d'attention sur le paquet `sentry-expo`.  2 vulnérabilités liées aux dépendances de ce paquet ne sont pas fixées par la dernière version de `sentry-expo` (version 3.1.3), nous laissons encore le paquet a la version voulue par expo (version 3.1.0).
> Com 2158- npm update

- __tests__/authentication.test.js
- environment.ts
- src/api/Authentication.ts
- src/api/Events.ts
- src/api/Users.ts
- src/context/AuthContext.ts
- src/core/helpers/asyncStorage.ts
master en api)
- Oui parce que n'a pas d'incidence sur l'api
- J'ai ajouté une variable d'environnement : 
- Cas d'usage : Si je me connecte en tant qu'apple, je suis redirigé vers baseURLStaging 
- Avec une auxiliaire uniquement présente en dev
- Vérifier que les appels sont bien redirigé sur dev
- Avec une auxiliaire uniquement présente en local 
- Verifier que les appels sont bien redirigé en local 
Les routes a tester : 
- Se connecter 
- Se déconnecter
- Mot de passe oublié : 
- Le mail est reconnu 
- On peut s’envoyer un mail de récupération de mdp 
- On peut envoyer le code de récupération 
- On peut mettre a jour le mdr 
- Les informations de l’utilisateur s’affichent bien sur la page Profil
- …
> COM-2237 redirect to staging url + fix removal of userid on logout

- src/components/modals/UpdateAppModal/index.tsx
master en api)
- Oui parce que je ne fais pas de changement au niveau des routes
- J'ai ajouté une variable d'environnement :
- Cas d'usage : Tant que l'app n'est pas vraiment sur les stores (en prod), la page n'existe pas donc je en sais pas trop comment tester...
> COM-2025 - add store redirections

- src/components/TimeStampingCell/index.tsx
- src/components/modals/CameraAccessModal/index.tsx
- src/components/modals/CameraAccessModal/styles.ts
- src/components/modals/modalStyles.ts
- src/screens/timeStamping/QRCodeScanner/index.tsx
master en api)
- Cas d'usage : Lorsque l'utilisateur veut horodater un évènement, il faut que l'accès a la camera soit autorisé. Apres appui sur le bouton commencer ou terminer pour horodater le debut ou la fin d'une intervention: 
- si l'acces a l'appareil photo est autorisé: l'utilisateur est redirigé vers la page d'horodatage par QR Code
- si l'acces a l'appareil photo n'est pas autorisé: 
- affichage de la modale "Vous n'avez pas autorisé l'accès à la camera..."
- dans réglages: accepter l'accès a l'appareil photo
- commencer/ terminer l'intervention --> la modale de permission d'accès a l'appareil photo apparait  
- si refus d'accès …
> COM-2247 requests access to the camera when user starts timeStamp

- .github/workflows/integration-tests.yml
- .github/workflows/ts-lint.yml
- package-lock.json
Node Js 14.16.0 => 14.18.0
Pré-requis
nvm install 14.18.0 (si pas déjà fait)
nvm use 14.18.0 sur compani-outils (penser à le changer dans la config iTerm si besoin)
npm install -g expo-cli (si pas déjà fait)
rm -rf node_modules && rm package-lock.json && npm i
> COM-2344: update node js

- src/components/EventDateTime/index.tsx
- src/screens/timeStamping/EventEdition/index.tsx
Fix des 3 bugs remontés par ulysse : 
- Sur ios 15 le datetimepicker n'est pas celui qu'on souhaite (spinner)
- sur les petits téléphones (iphone SE 1ère gen par exemple) lorsque le datetimepicker de la date de début est affiché on ne peut pas modifier la date de fin
- sur android on peut mettre une date de fin inférieur à celle de début (impossible à fix car les props minimum / maximumDate ne fonctionnent pas sur android, j'ai donc fait une gestion d'erreur)
> Com 2540 ou COM 2470 fix

- src/api/Events.ts
- src/components/EventFieldEdition/index.tsx
- src/components/form/Input/index.tsx
- src/components/form/Input/styles.ts
- src/core/data/constants.ts
- src/screens/timeStamping/EventEdition/index.tsx
- src/screens/timeStamping/EventEdition/styles.ts
- src/screens/timeStamping/EventEdition/types.ts
- src/types/EventType.ts
master en api)
- Cas d'usage : ETQ auxiliaire, sur la page edition d'une intervention, je peux ajouter un déplacement véhiculé effectué avec le beneficiaire. 
- Si aucun déplacement enregistré: le bouton cliquable `Ajouter un déplacement véhiculé avec le/la beneficiaire`
- Si un déplacement a deja été enregistré pour cette intervention l'input indiquant le nombre de km parcourus apparait 
- Si l'intervention est facturée, on ne peut plus editer le nombre de km (si le nbre de km vaut 0, le bouton cliquable n'apparait pas)
> COM-2527 - can add km details

- src/components/ErrorMessage/styles.ts
- src/components/EventDateTimeEdition/index.tsx
- src/components/EventFieldEdition/index.tsx
- src/core/data/constants.ts
- src/screens/timeStamping/EventEdition/index.tsx
- src/screens/timeStamping/EventEdition/types.ts
master en api)
- J'ai ajouté une variable d'environnement : -np 
- Ajout d'une validation sur le kmDuringEvent: lorsque l'utilisateur entre un nombre invalide ou des lettres --> erreur au moment de l'enregistrement.
Pour tester: Sur la page d'édition d'un evenement, dans le champ `Déplacement vehiculé avec le/la beneficiaire`: 
- saisir un nombre invalide --> erreur lors de l'enregistrement
- si le clavier est numérique, retirer type={NUMBER} pour pouvoir saisir des lettres --> erreur lors de l'enregistrement
> COM-2597 - add validation before saving changes

- src/screens/timeStamping/EventEdition/index.tsx
master en api)
- Non parce que migration mongoose --> erreur `options usecreateindex, usefindandmodify are not supported`
- Cas d'usage : Modification du titre de l'input `Déplacement véhiculé avec bénéficiaire`
> COM-2527 - change kmDuringEvent input title

- src/components/EventFieldEdition/index.tsx
- src/components/EventFieldEdition/styles.ts
- src/screens/timeStamping/EventEdition/index.tsx
master en api)
- Cas d'usage : Retour de Romain: sur Android, lorsque l'input est selectionné les ombres sur les cotés sont rongées par la marge de l'écran. 
- J'ai rectifié pour les input de la fiche beneficiaire dans le ticket COM-2611.
- Dans ce ticket je fais la modification sur les inputs de la page `EventEdition`
Romain propose de retravailler le style de l'input pour qu'il devienne dynamique. (cf [son commentaire](https://compani.atlassian.net/browse/COM-2610?focusedCommentId=12621&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-12621) )
Ca demande de faire pas mal de modifs, que pensez-vous de …
> COM-2610 -fix shadow display on Android

- src/screens/timeStamping/EventEdition/index.tsx
---
---
- Périmètre interfaces / rôles :
- Finalement, le comportement de “enregistrer” gagne à être différent selon la page sur laquelle on est
- sur une page “intervention” : on se rend sur cette page en général parce qu’on veut éditer quelque chose. Une fois la modif faite, on veut revenir sur l’endroit où on était avant => le bouton “enregistrer” doit enregistrer puis revenir en arrière
- sur une page “bénéficiaire” : on se rend sur cette page pour consulter de l’information. Il se peut que je décide de faire une modif, mais je suis avant tout là pour consulter => le bouton “enregistrer” doit enregistrer puis rester sur la page
- Design input de type texte (comme par exemple le champ “note”) : viser le même design que le champ “transport pour aller à l’intervention”
Pour ce dernier …
> COM-2660-2 - fix Romain's reviews

- src/screens/CustomerProfile/index.tsx
---
---
- Cas d'usage : Depuis la fiche beneficiaire, je peux editer l'auxiliaire référent 
- depuis la webApp, mettre `Pas d'auxiliaire référent` pour un beneficiaire
- sur mobile, aller sur la fiche de ce beneficiaire
- sélectionner un auxiliaire référent
- enregistrer
- verifier que le changement a bien été fait 
> COM-2693 - fix bug when customer hasn't referent auxiliary

- src/components/EventCell/index.tsx
- src/components/EventCell/styles.ts
- src/screens/timeStamping/QRCodeScanner/styles.ts
---
---
- Cas d'usage : 
Correction de deux bugs : 
- Sur l'Agenda, lorsque mon bénéficiaire à un nom long, l'icône pour horodater pouvait sortir de la cellule
- Sur le scanner, sur les grands écrans, on pouvait encore avoir le bug où on ne voyait plus le bouton d'horotage manuel. Le soucis avait été corrigé sur les petits écran mais pas les grands
Tester la correction des 2 bugs sur le maximum d'appareil possible
> COM-2741 - Fix on large screen

- src/components/PersonEditionModal/index.tsx
- src/types/UserType.ts
---
---
- Cas d'usage : je peux acceder a une fiche beneficiaire meme si celui-ci a un aidant sans prenom
- Comment tester ? : se creer un compte auxiliaire avec une intervention aujourd'hui. Ajouter au beneficiaire de l'intervention un aidant sans prenom. Essayez d'acceder a la page profile du beneficiaire sur l'application. 
> COM-2725 fix bug on customer profile

- src/components/EventCell/index.tsx
- src/components/EventCell/styles.ts
- src/styles/metrics.ts
---
---
- Cas d'usage : l'icone "check" d'un horodatage (debut ou fin) sur la page agenda etait trop grosse pour Romain. Je l'ai raccourcis et épaissie 
- Comment tester ? : comparer l'icone avec la maquette figma
> COM-2739-2 shorten size of 'check' icon

- src/screens/timeStamping/EventEdition/index.tsx
---
---
- Périmètre interfaces / rôles : Auxiliaire
- Cas d'usage : 
- lorsque j'édite l'heure d'une intervention, si l'heure est invalide et que j'enregistre, le message d'erreur s'affiche et je ne suis pas redirigé vers la page précédente 
- Rmq: Bug présent uniquement sur Android. Sur IOS, le sélecteur d'heure permet de definir une date minimale pour l'heure de fin (heure de fin minimale = heure de debut de l'intervention) donc pas possible de definir une heure de fin antérieure a l'heure de début
- editer l'heure d'une intervention de sorte a ce que l'heure de fin soit antérieure a l'heure de debut 
- enregistrer
- le message d'erreur s'affiche et on n'est pas redirigé vers la page précédente 
> COM-2765 - fix bug

- src/screens/timeStamping/EventEdition/index.tsx
---
---
- Cas d'usage : fix du bug remonté par Sophie (cf commentaires du ticket)
- Comment tester ? 
- depuis la webapp, annuler une intervention 
- Cote mobile: 
- vérifier que l'on voit bien les 2 icônes correspondant aux conditions d'annulation + la personne a l'origine de l'annulation
-  editer l'heure de l'intervention et d'autres champs
- revenir sur la page d'edition d'intervention et verifier que les infos d'annulation sont tjs affichées 
- Sur la webapp: verifier que le planning s'affiche correctement sur la semaine de l'intervention
> COM-2746 - add isCancelled to eventPayload

- src/components/ToastMessage/styles.ts
---
---
- Périmètre interfaces / rôles : ETQ auxiliaire
- Cas d'usage : Lorsque j'édite la fiche d'un beneficiaire, un toast-message apparait.
- modifier la fiche d'un beneficiaire puis enregistrer
- verifier que le toast message est visible
> COM-2762 - add padding on android

- src/context/AuthContext.ts
---
---
- Périmètre interfaces / rôles : mobile outils - auxiliaire
- Cas d'usage : suppression de la fonction pour fixer le refreshToken, retour à l'ancienne gestion
- passer  `if (asyncStorage.isTokenValid(companiToken, companiTokenExpireDate))` à `if (false)` pour rentrer dans le else
- se connecter et fermer l’app
- re-ouvrir l’app => je suis bien connecté
> COM-2939: remove deprecated function

- src/styles/colors.ts
---
---
- Périmètre interfaces / rôles : tous
- Cas d'usage : refacto des couleurs
vu avec Romain : 
- on implémente orange plutôt que new-orange 
- on conserve peach100 et 200 même s'ils sont pas dans figma
- orange-50 vaut new-orange-50
- Comment tester ? : s'assurer que les ombres s'affichent bien
> COM-2931: refacto colors

- .github/workflows/integration-tests.yml
- .github/workflows/ts-lint.yml
Mise à jour des library actions/checkout et actions/setup-node car les actions utilisant node12 est bientot déprécié.
> COM-3371 update libraries for github actions
